### PR TITLE
Convert EX-RAIL summary tables to reST list-table

### PR DESCRIPTION
**Pull request by cjmayo**
I realise the tables did use list-table before. Possibly the difference here is to us `:widths: auto` to let the browser calculate the columns?

### CODE REVIEW

**Comment by FrightRisk** [comment]
I'm not sure. Does this fix the horrible table I put in there to deal with not having to have the horizontal scroll bar to see the whole table on smaller screens?

**Comment by FrightRisk** [comment]
The table should look like this, I duplicated the colors from the theme:

image

This is what I see in the RST file. I don't know how to merge something from your repo into a test branch in our repo before I merge it into the main branch. 

image

**Comment by FrightRisk** [comment]
I'm assuming it will work and that the theming is just not applied looking at it in github. Where is it picking up the table cell colors? Did you just give names to these:

tr:nth-child(even) {
      background-color: #E0E0E0;
    }
    tr:nth-child(odd) {
      background-color: #F3F6F6;
    }

I see the referece to seafoam and slate gray or similar.

**Comment by cjmayo** [comment]
> I'm not sure. Does this fix the horrible table I put in there to deal with not having to have the horizontal scroll bar to see the whole table on smaller screens?

Yes. I believe it adapts to more smaller screens e.g. 360x740 which the current one creates a scroll bar for.

**Comment by cjmayo** [comment]
> I'm assuming it will work and that the theming is just not applied looking at it in github. Where is it picking up the table cell colors? Did you just give names to these:
> 
> tr:nth-child(even) { background-color: #E0E0E0; } tr:nth-child(odd) { background-color: #F3F6F6; }
> 
> I see the referece to seafoam and slate gray or similar.

I didn't add a specification for the colors. The RTD theme gives:

```css
.rst-content table.docutils:not(.field-list) tr:nth-child(2n-1) td
rgb(243, 246, 246)

.rst-content table.docutils td
transparent
```
Which can be seen already at: https://dcc-ex.com/reference/hardware/i2c-devices.html#id2

This is quite a bit lighter. I did look at it, but couldn't see how to override the RTD theme just for the EX-RAIL tables. On the other hand changing all the tables (including e.g. the I2C one) would be possible.

**Comment by FrightRisk** [comment]
I like the darker table scheme. It also matches the menu to the left when it is expanded which is why I went with it. Teach me CSS Jedi Master ;) How to we change it? If I had my druthers, I would change it all to be in the blue family of turquoise, but that isn't so necessary.

image

**Comment by cjmayo** [comment]
Alas no great wisdom here - just reverse engineering using Firefox Inspect. Added as a new commit.

**Comment by FrightRisk** [comment]
Is this moot now and only merge the new changes or do we need this resolved, merged, and then the new one merged?

**Comment by FrightRisk** [comment]
Not Sure I like how it turned out. Here is a comparison. Do we want the left column to not be wrapped? It is wrapped on the old one. Also the headings are centered in the old one. And which do we prefer, gray and white rows or gray and dark gray?
image
new
image

**Comment by FrightRisk** [comment]
I reverted it. Wish I had more time to really learn more about css and even github since I'm not sure how to show this as a PR again. Since I merged it, it became closed, and even after reverting, it is still just showing as "merged". The biggest issue is that the scrollbar is still there in this PR. It widened the left column and then left the right column at some set width, perhaps the width of the longest text? In any case, it doesn't wrap and then you don't see the scroll bar and are not sure what to do unless you scroll a mile down to the bottom of the table. 

We need something where the cells have a set starting width unless the screen is too small, in which case it just wraps the text. We have to keep a scrollbar from enabling. In a long table, people won't see the scrollbar. I imagine you may be able to click in a cell and use the arrow keys? I have no idea, but that won't work either. Your idea to make this some kind of class will work if we can figure out how to duplicate everything in the css I have now.

**Comment by FrightRisk** [comment]
And no idea how to decipher this, but clearly the revert did not revert everything. But trying to compare the old page to the new, the table items are pointing to completely different settings, my original:

image

New one:

image

**Comment by cjmayo** [comment]
Trying to think up a way to preview PRs. Best (easy) way I can come up with is to use our own GitHub Forks and enable Pages publishing. And merging the PR changes into the fork's sphinx branch.

On the scrollbars - the RTD theme is enabling them, I've got a proposed override for that:
979fb9efd8627b114f1ff04615eb69963739db70

That can be seen on my Fork: https://cjmayo.github.io/dcc-ex.github.io/automation/EX-RAIL-summary.html

The branch would need updating anyway as the content has changed since in the sphinx branch. So no loss there.

**Comment by cjmayo** [comment]
That left no scrollbars at all. I guess that isn't what is wanted - there needs to be a page scrollbar.

**Comment by FrightRisk** [comment]
So the vertical scrollbar went away? The raw html worked, so there must be an equivalent "right" way to do it.

**Comment by cjmayo** [comment]
No, I shouldn't have used the plural there. I was just talking about the horizontal scrollbar.

I've added  2b228abe which is now live on my GitHub pages. Looks like this might be working and allowing a horizontal page scrollbar.

**Comment by FrightRisk** [comment]
Is that the same as this? This seems to work fine on my laptop browsers and adjusting the window size to see the table cells wrap: https://cjmayo.github.io/dcc-ex.github.io/automation/EX-RAIL-summary.html. If that is working, let's put that into the sphinx branch

**Comment by cjmayo** [comment]
Yes, that was updated with the latest CSS.

I'll prepare an updated version with the latest content.

**Pull request merged**
