### PR TITLE
Update track-manager.rst

### PR DESCRIPTION
**Pull request by Kcsmith0708**
Edited
EX-RAIL  to  EXRAIL
Track to District
added Serial monitor display of A & B tracks
Edited and added info to ED choices 2.

Highlighted & Moved Engine Driver descriptions above the images. Having formatting issues with the descriptions moving under the Image above it and next to the wrong Figure#

Need to see this published to see if the headers are correct over the images

### CODE REVIEW

**Review by Kcsmith0708 — COMMENTED** [review]
added space above Images

**Review by Kcsmith0708 — COMMENTED** [review]
formatting position of ED screens

**Comment by Kcsmith0708** [comment]
ED screen shots positions are not passing checks

**Comment by peteGSX** [comment]
Fixed build errors due to RST syntax issues, have removed the spaces from the `<=>` command as they are not required.

**Comment by Kcsmith0708** [comment]
Thank you for cleaning up the RST syntax

I put the < = > space in just for visibility. 
We actually only use <> in the IDE serial monitor.
All other interfaces (i.e., JMRI, Engine Driver, DCCppCab, EX-WebThrottle) don't use <> brackets.

On this TrackManager webpage,  I missed the EX-RAIL names on headers for the script examples.
Could you please change these to EXRAIL for me?
Thx.

**Pull request merged**
