### PR TITLE
Added a guide for the mySetup.h file

### PR DESCRIPTION
**Pull request by mystcb**
Having just had to work my way through this, thought it best to contribute back and write some documentation on the `mySetup.h` file and how it works. Hopefully, this can help someone else in the future.

This is my first contribution, so I am hoping I have completed everything correctly. Any problems, please let me know!

### CODE REVIEW

**Comment by mystcb** [comment]
Thanks @Ash-4 for the comments! Made a few minor changes, but will double check when I am back home:

- Updated the example to copy your setup exactly, added some additional comments about comments as well
- Updated the SETUP(""), to include the `<>`, removed the small comment about taking them out
- Minor changes to the text to make it suit the changes

The only bit I have not changed is the Hornby R7150 example, I will be heading home later this evening so will run some more tests and get back to you. I believe I tried the `ACK LIMIT` and did not get any success, but the `MIN 30` was the only change that seemed to work. I will have another play when I get back and see if I can try any of the other combinations you have mentioned. If I get somewhere, I will update the example at the top.

Thank you again, and I hope that the changes made so far are OK.

**Comment by Asbelos** [comment]
I hope this helps... randomly changing ack limit and min/max isn't the best way... 
What you should do is use <D ACK ON> AND THEN <R> to get a diagnostic trace of what the command station is getting back from the decoder, then you can decide what the reason for failure is and thus how to adjust the parameters to resolve it... 
E.g you may be able to see that the decoder is responding with a weak pulse, or one that is too short or long.

**Comment by mystcb** [comment]
Had a bit of a trial again today, and found the `LIMIT` wasn't giving me any good response back, however I did spot that the diagnostic output showed a pulse of between 2600-2700uS. Setting `<D ACK MIN 2600>` continued to do the trick (so 30uS was just a guess at going too low).

Attached below is the diagnostic information that shows the pulse rate I was seeing. (This is a working response with the lower 2600uS minimum set).

Hoping this helps a bit, but also updated the documentation to match this new finding too.

Let me know if this is OK, or if you would like me to do a little more work on this - more than happy to help where I can!

```
<* Auto Prog power on *>
<* ACK baseline=0/0mA Threshold=20/59mA Duration between 2600us and 8500us *>
<* VB cv=19 value=0 *>
<* ACK after 20mS max=103/307mA pulse=2668uS samples=217 gaps=0 *>
<* V0 cv=29 bit=5 *>
<* ACK after 41mS max=82/245mA pulse=2668uS samples=185 gaps=0 *>
<* V0 cv=1 bit=6 *>
<* ACK after 20mS max=78/233mA pulse=2612uS samples=233 gaps=0 *>
<* V0 cv=1 bit=5 *>
<* ACK after 22mS max=98/293mA pulse=2784uS samples=235 gaps=0 *>
<* V0 cv=1 bit=4 *>
<* ACK after 31mS max=76/227mA pulse=2668uS samples=89 gaps=0 *>
<* V0 cv=1 bit=3 *>
<* NO-ACK after 146mS max=0/0mA pulse=0uS samples=112 gaps=0 *>
<* V0 cv=1 bit=2 *>
<* ACK after 21mS max=76/227mA pulse=2784uS samples=239 gaps=0 *>
<* V0 cv=1 bit=1 *>
<* ACK after 22mS max=77/230mA pulse=2668uS samples=238 gaps=0 *>
<* V0 cv=1 bit=0 *>
<* ACK after 22mS max=76/227mA pulse=2784uS samples=244 gaps=0 *>
<* VB cv=1 value=8 *>
<* ACK after 21mS max=100/299mA pulse=2616uS samples=241 gaps=0 *>
<* Auto Prog power off *>
<* Callback(8) *>
<r 8>
```

**Comment by FrightRisk** [comment]
Hi Colin, thanks for the help! I need to merge something right now and look closer at what you created and then pull that in next. I should get to it tomorrow. I gave a quick look, and it's great. You figured out our structure and how to update the index, etc. So this is an easy add. Thank you for contributing to the project!

**Pull request merged**
