### PR TITLE
Enable autosectionlabel_prefix_document

### LINKED ISSUE #100: Adding document name to ref and doc tags
@cjmayo, @Condo-Colin Making this an issue instead of a thread in the PR since when you close it, it doesn't make sense to keep a conversation going there. I don't fully understand autosectionlabel_prefix_document. Right now, every title is a link which for the first "make github" command you will get a lot of "duplicate label" warnings. But they go away until some other action happens. Not sure what that is. From the quick read, it looks like autosection label puts a prefix on the front of every title automatically? Or do you have to do it? Ex: hardware:how to, software:how to. Perhaps it is manualy, which is why you added this:

"If you agree I can probably add a commit here that adds the document to these :doc: and :ref: targets (not something I want to do if it isn't going to be used."

I think we should use it and make that a standard just like we have for which character underline is use for which heading, how we use "note", etc.

### PR DESCRIPTION
**Pull request by cjmayo**
Expected to fail the check because only one :ref: is converted to autosectionlabel_prefix_document format. Just an illustration for now. I will add to this (replacing the WIP commit).

Closes: #100.

### CODE REVIEW

**Comment by FrightRisk** [comment]
I guess it is one or the other, if you enable that setting, it breaks the others. If it passed the check for that one change and we see the warnings got away as they are changed, that will work well. We should also have a note in the CONTRIBUTING.md and maybe a WiKi on all our standards including this for for "how to include hyperlinks".

**Comment by FrightRisk** [comment]
Where are we on this? Will it pass checks now?

**Comment by cjmayo** [comment]
Still more work to do. I started on it, realised it was not great for references within the same page - as far as I can see you still have to prefix the reference with the full name of the page - thought Sphinx could do better, and came up with a way that seemed to work: https://github.com/sphinx-doc/sphinx/pull/10103.

I'd like to say I had been waiting to see if there was any feedback on the Sphinx PR, but really I have just been too busy.

I will get back to these. Even if Sphinx changes it would then mean waiting for its next release (although it is possible to pip install a snapshot from Git. That's fine by me because I can easily patch my local copy automatically but might be a bit of a pain for everyone else).

**Comment by cjmayo** [comment]
References updated - checks now pass.

Standards documentation in progress.

**Comment by cjmayo** [comment]
Ready to go now. This does also put a reference to the website.rst in CONTRIBUTING.md and removed the Submission Procedure which is duplicated for easier maintenance.

**Pull request merged**
