### PR TITLE
pwa-changes

### PR DESCRIPTION
**Pull request by matt-vdv**
These are the changes needed to complete the migration to the new WebThrottle-EX rollout system.

Note - Not to be merged till after @frightrisk has set up github pages

### CODE REVIEW

**Comment by matt-vdv** [comment]
@FrightRisk I have fixed the conflict

**Comment by FrightRisk** [comment]
I think it looks ready to merge. I'll download that version and test it.
Then merge. Then I have a bunch of stuff in the frightrisk-changes branch
to will have to pull these changes into mine and push

**Comment by FrightRisk** [comment]
Yeah, I have no idea how to properly merge this. I think there could be files that would obliterate other people's settings. For example, it looks like there is a Visual Studio Code settings.json and this wants to change that. It wants to add a path for usr/local/bin/python. Is that correct? I'm on windows. We may need to see what has to be put in .gitignore

**Comment by matt-vdv** [comment]
@FrightRisk yes, probably best to put the .vscode in the gitignore

**Comment by FrightRisk** [comment]
Anyone know the correct way to do this? I can put it on the project .gitignore, though the current thinking is you should put it in a global gitignore in the root of your local machine. Not sure how to do that yet. But my big concern is how does this work if it may already be tracked? I put that in my machine and delete it in github, will that work? Or will I find it is tracked and it will delete the .gitignore on my machine the next time I pull?

**Comment by matt-vdv** [comment]
@FrightRisk If you add it to the gitignore locally, when you push it will stop tracking and remove the file(s), as far as I am aware...

**Comment by FrightRisk** [comment]
Everything is working! Great job guys!! I am tweaking some things and there
will be more web content up soon. What is the process now for making
changes? Which branch is for development? And how do things get into
_build? For example, there is a misspelling I need to correct, where do I
do it and how to I make sure it is merged and buit wherever it needs to be?

**Pull request merged**
