### PR TITLE
Fix links and warnings

### PR DESCRIPTION
**Pull request by cjmayo**
This started as fixing broken links but it grew into resolving the warnings. I don't mind splitting it up if that would help.

- Fix broken internal links. This includes matching the case of the image filenames. Doesn't seem to matter for pages served over http but it does for accessing them locally on Linux, and that is also much the quicker way to check the links.
- Fix broken external links
- Using :doc: and :ref: for internal links instead of the generated HTML pages allows Sphinx to check the targets really exist, and means they could work if a non-HTML builder was used. I realise a bit of an effort to review manually. This was done almost completely using a regular expression, and as well as Sphinx checking the links I have also checked the generated HTML.
- Fix the Other section heading at the bottom of the DCC++ EX Command Summary
- There is a bit of a cheat in that autosectionlabel warnings, `WARNING: undefined label:` are suppressed - this could be fixed by using `autosectionlabel_prefix_document` but there are a lot of them, and I haven't looked to see how difficult that would be.
- Other minor warnings fixed.
- Turn warnings into errors. I think this will result in the GitHub check failing. This is perhaps a bit personal choice (easy to remove from the PR). But for me it is worth having to fix a few syntax errors to catch broken links and missing headings.

### CODE REVIEW

**Comment by Condo-Colin** [comment]
Thanks very much for your effort here CJ! Welcome to the fun!
For interest, what made you choose to join in here? Your input is appreciated!
I'll make sure the boss gets a look at this for you.

**Comment by cjmayo** [comment]
> Thanks very much for your effort here CJ! Welcome to the fun! For interest, what made you choose to join in here? 

I was looking for a way to build an automated layout and am really happy to find an Open option. I'm copy and paste only with C++, but Sphinx and Python I can do. And a lot of reading the docs to get going - there is plenty of good content there. I'm just booted up with an LCD display and my first EX-RAIL script that can respond to a switch input. I hope I'll be able to contribute some actual words from a newbie point of view in due course.

With the changes I should have said something about "Exclude placeholder pages" - the solution in that commit was picked because it made no difference to the site (well from available links). Adding the pages to a toctree would also work.

**Comment by Condo-Colin** [comment]
That's awesome mate!
You'll have some good yarns with Chris, the programmer whose idea the automation on top of DCC++ was.
You should join our Discord if you haven't already and say Gudday!
https://discord.gg/AUxvMZH9VZ
There's a few of us working on the website, but it needs quite a bit of work in spots. That's how I got involved, was skimming thru for "typoreadagrams", to help with image & clarity! So learning about GitHub and .rst along the way. 🤓

**Comment by FrightRisk** [comment]
@cjmayo Thanks again for the help. I think I used ref tags in a few places and got lazy because it was easier to cut and paste the html. I meant to go back and make things more elegant at some point. I started to include the tag to manually name headings because there are so many duplicate labels using "explicit targets". If every section has a "Getting started" or "hardware", then you either have to make the title unique like "Hardware (Mega)" vs. "Hardware (Uno)" You can see some of that in the rst files as well. Anything else you can help with? Please join us and help create the next version of the page, or at least get what is there in better shape. I don't suppose you can do web page work like CSS and Javascript, can you? I am looking for help on our web throttle also.

Fred

**Comment by FrightRisk** [comment]
How are we going to remember to include them when we are ready to release these placeholder pages?

exclude_patterns = [
    '_build', 'Thumbs.db', '.DS_Store',
    'reference/software/programming-locos.rst',
    'throttles/physical-knobs.rst',
    ]

I'll squash and merge when we've finished this thread

**Comment by cjmayo** [comment]
>  I think I used ref tags in a few places and got lazy because it was easier to cut and paste the html. I meant to go back and make things more elegant at some point. I started to include the tag to manually name headings because there are so many duplicate labels using "explicit targets". If every section has a "Getting started" or "hardware", then you either have to make the title unique like "Hardware (Mega)" vs. "Hardware (Uno)" You can see some of that in the rst files as well.

I think [autosectionlabel_prefix_document
](https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html?highlight=autosectionlabel_prefix_document#confval-autosectionlabel_prefix_document) would be the answer. If you agree I can probably add a commit here that adds the document to these :doc: and :ref: targets (not something I want to do if it isn't going to be used...).

Else it means manually adding labels as done in throttles/srcpclient.rst.

> Anything else you can help with? Please join us and help create the next version of the page, or at least get what is there in better shape. I don't suppose you can do web page work like CSS and Javascript, can you? I am looking for help on our web throttle also.

I don't want to get expectations up too much! I tend to focus on one project at a time and then move on (often coming back now and then). I can do a bit of CSS and Javascript - but at a level somewhere between my C++ and Python. I don't plan to use a computer in my setup. I am a bit tempted to write a basic Python DCC++ EX client using pyserial to use during the build/learning process - just to save typing in the commands but still know exactly what is being sent. Don't know if I will and maybe I should just use WebThrottle.

> How are we going to remember to include them when we are ready to release these placeholder pages?
> 
> exclude_patterns = [ '_build', 'Thumbs.db', '.DS_Store', 'reference/software/programming-locos.rst', 'throttles/physical-knobs.rst', ]

I agree I think that is an issue.

But the toctree warnings are a problem if deciding to enforce no warnings. On balance I would suggest to instead add them to toctree(s) now and publish them as they are - maybe it even encourages someone reading to write something! (I was just trying not to change things myself and didn't think about where they should go).

> I'll squash and merge when we've finished this thread

I can split it up into separate PRs if it would make sense in the history and help e.g. get on and get the broken links done.

**Comment by cjmayo** [comment]
Another option for the placeholders would be to delete them from the sphinx branch, create a new branch and add them (as a new commit to be obvious and merge/rebaseable).

**Comment by FrightRisk** [comment]
I have to be honest, with the DCC-EX project alone, there is unlimited work and limited time. Therefore, I am trying to find people like @Condo-Colin and others to take some of the load. The more I can be in an approve/steer role, the better.

I don't fully understand autosectionlabel_prefix_document. Right now, every title is a link which for the first "make github" command you will get a lot of "duplicate label" warnings. But they go away until some other action happens. Not sure what that is. From the quick read, it looks like autosection label puts a prefix on the front of every title automatically? Or do you have to do it? Ex: hardware:how to, software:how to. Perhaps it is manualy, which is why you added this:

"If you agree I can probably add a commit here that adds the document to these :doc: and :ref: targets (not something I want to do if it isn't going to be used."

I think we should use it and make that a standard just like we have for which character underline is use for which heading, how we use "note", etc.

**Pull request merged**
